print("Hello to the CI test")
print ("Give 2 numbers for addition operation")
num1 = float(input(" Please Enter the First Value Number 1: "))
num2 = float(input(" Please Enter the Second Value Number 2: "))
print("Result: ", num1+num2)
